[workspace]
resolver = "2"
members = [
  "admin",
  "api-client",
  "auth",
  "backends",
  "cargo-shuttle",
  "codegen",
  "common",
  "common-tests",
  "deployer",
  "gateway",
  "logger",
  "proto",
  "provisioner",
  "resource-recorder",
  "runtime",
  "service",
]
exclude = [
  "examples",
  "resources",
  "services",
]

[workspace.package]
version = "0.49.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/shuttle-hq/shuttle"

# https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacedependencies-table
[workspace.dependencies]
shuttle-api-client = { path = "api-client", version = "0.49.0", default-features = false }
shuttle-backends = { path = "backends", version = "0.49.0" }
shuttle-codegen = { path = "codegen", version = "0.49.0" }
shuttle-common = { path = "common", version = "0.49.0" }
shuttle-common-tests = { path = "common-tests", version = "0.49.0" }
shuttle-proto = { path = "proto", version = "0.49.0" }
shuttle-service = { path = "service", version = "0.49.0" }

anyhow = "1.0.66"
async-trait = "0.1.58"
axum = { version = "0.6.13", default-features = false }
base64 = "0.21.5"
bollard = "0.15.0"
bytes = "1.3.0"
cargo_metadata = "0.18.1"
chrono = { version = "0.4.34", default-features = false }
clap = { version = "4.2.7", features = ["derive"] }
colored = "2.0.0"
comfy-table = "6.2.0"
crossterm = "0.27.0"
ctor = "0.2.5"
dirs = "5.0.0"
dunce = "1.0.4"
flate2 = "1.0.25"
fqdn = "0.3.2"
futures = "0.3.27"
headers = "0.3.8"
home = "0.5.4"
http = "0.2.8"
http-body = "0.4.5"
hyper = "0.14.23"
# not great, but waiting for WebSocket changes to be merged
hyper-reverse-proxy = { git = "https://github.com/chesedo/hyper-reverse-proxy", branch = "bug/host_header" }
jsonwebtoken = "9.0.0"
once_cell = "1.16.0"
opentelemetry = "0.21.0"
opentelemetry_sdk = { version = "0.21.0", features = ["rt-tokio", "logs"] }
opentelemetry-http = "0.10.0"
opentelemetry-otlp = { version = "0.14.0", features = ["logs", "http-proto", "reqwest-client", "reqwest-rustls"] }
opentelemetry-proto = "0.4.0"
opentelemetry-contrib = { version = "0.4.0", features = ["datadog"] }
opentelemetry-appender-tracing = "0.2.0"
percent-encoding = "2.2"
pin-project = "1.0.12"
portpicker = "0.1.1"
pretty_assertions = "1.3.0"
prost = "0.12.1"
prost-types = "0.12.1"
rand = "0.8.5"
reqwest = { version = "0.11.13", default-features = false, features = ["rustls-tls"] }
ring = "0.17.4"
rmp-serde = "1.1.1"
semver = { version = "1.0.17", features = ["serde"] }
serde = { version = "1.0.148", default-features = false }
serde_json = "1.0.89"
sqlx = { version = "0.7.1", features = ["runtime-tokio", "tls-rustls"] }
strfmt = "0.2.2"
strum = { version = "0.26.1", features = ["derive"] }
tar = "0.4.38"
tempfile = "3.4.0"
test-context = "0.3.0"
thiserror = "2"
tokio = "1.22.0"
tokio-stream = "0.1.11"
tokio-tungstenite = { version = "0.20.1", features = [
  "rustls-tls-webpki-roots",
] }
tokio-util = "0.7.10"
toml = "0.8.2"
toml_edit = "0.20.2"
tonic = "0.10.2"
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = { version = "0.1.37", default-features = false }
tracing-opentelemetry = "0.22.0"
tracing-subscriber = { version = "0.3.16", default-features = false, features = [
  "registry",
  "json",
] }
typeshare = "1.0.3"
ttl_cache = "0.5.1"
ulid = "1.0.0"
url = "=2.5.2" # https://github.com/servo/rust-url/issues/992
uuid = "1.2.2"
wiremock = "0.6.0"
zeroize = "1.6.0"
